"""empty message

Revision ID: 3c9ab4a896dd
Revises: 02f35341463b
Create Date: 2024-09-29 22:01:37.798643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c9ab4a896dd'
down_revision = '02f35341463b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('guid', sa.String(length=255), nullable=False),
    sa.Column('create_datetime', sa.DateTime(), nullable=True),
    sa.Column('modify_datetime', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addresses')
    # ### end Alembic commands ###
